"use client"

import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Printer } from "lucide-react"

interface Payment {
    id: string;
    amount: number;
    method: string;
    reference: string;
    created_at: string;
    date?: string;
    tenant_name?: string;
    tenant?: {
        name: string;
        unit?: {
            unit_number: string;
            property?: {
                name: string;
            }
        }
    }
}

interface ReceiptModalProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    payment: Payment | null;
}

export function ReceiptModal({ open, onOpenChange, payment }: ReceiptModalProps) {
    if (!payment) return null;

    const handlePrint = () => {
        window.print();
    };

    const formattedDate = new Date(payment.created_at || payment.date || "").toLocaleDateString("en-KE", {
        year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
    });

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="max-w-md bg-white">
                <DialogHeader>
                    <DialogTitle>Payment Receipt</DialogTitle>
                </DialogHeader>

                <div id="printable-receipt" className="border p-6 rounded-md space-y-4 bg-slate-50">
                    <div className="text-center border-b pb-4">
                        <h3 className="text-xl font-bold uppercase tracking-wider">Rent Receipt</h3>
                        <p className="text-sm text-muted-foreground">Receipt #{payment.id}</p>
                        <p className="text-xs text-muted-foreground">{formattedDate}</p>
                    </div>

                    <div className="space-y-2 text-sm">
                        <div className="flex justify-between">
                            <span className="text-muted-foreground">Received From:</span>
                            <span className="font-semibold">{payment.tenant_name || payment.tenant?.name}</span>
                        </div>
                        <div className="flex justify-between">
                            <span className="text-muted-foreground">Property/Unit:</span>
                            <span className="font-medium">
                                {payment.tenant?.unit?.property?.name || "N/A"} - {payment.tenant?.unit?.unit_number || "N/A"}
                            </span>
                        </div>
                        <div className="flex justify-between">
                            <span className="text-muted-foreground">Payment Method:</span>
                            <span className="font-medium">{payment.method}</span>
                        </div>
                        <div className="flex justify-between">
                            <span className="text-muted-foreground">Reference:</span>
                            <span className="font-mono">{payment.reference || "N/A"}</span>
                        </div>
                    </div>

                    <div className="border-t pt-4">
                        <div className="flex justify-between items-center">
                            <span className="font-bold text-lg">Amount Paid:</span>
                            <span className="font-bold text-xl text-indigo-600">KES {payment.amount.toLocaleString()}</span>
                        </div>
                    </div>

                    <div className="text-center pt-8 text-xs text-muted-foreground">
                        <p>Thank you for your payment.</p>
                        <p className="mt-1">Generated by Renting Management System</p>
                    </div>
                </div>

                <div className="flex justify-end space-x-2 print:hidden">
                    <Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button>
                    <Button onClick={handlePrint}>
                        <Printer className="mr-2 h-4 w-4" /> Print
                    </Button>
                </div>

                <style jsx global>{`
           @media print {
              body * {
                visibility: hidden;
              }
              #printable-receipt, #printable-receipt * {
                visibility: visible;
              }
              #printable-receipt {
                position: absolute;
                left: 0;
                top: 0;
                width: 100%;
                border: none;
                background: white;
              }
              .no-print {
                display: none;
              }
           }
        `}</style>
            </DialogContent>
        </Dialog>
    )
}
